# Generated by Django 6.1.1 on 2026-09-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Leitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispositivo", models.CharField(max_length=50)),
                ("pulsos", models.IntegerField()),
                ("chuva_mm", models.DecimalField(decimal_places=3, max_digits=10)),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
